"""empty message

迁移 ID: 47de49e72a32
父迁移: e2639b1b97f6
创建时间: 2026-04-05 19:41:41.654570

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '47de49e72a32'
down_revision: str | Sequence[str] | None = 'e2639b1b97f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gacha_drop_record', schema=None) as batch_op:
        batch_op.alter_column('scene_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gacha_drop_record', schema=None) as batch_op:
        batch_op.alter_column('scene_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
