"""empty message

迁移 ID: e2639b1b97f6
父迁移: 
创建时间: 2026-04-04 21:04:11.727941

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e2639b1b97f6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_config')),
    info={'bind_key': 'model'}
    )
    op.create_table('gacha_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gacha_template')),
    info={'bind_key': 'model'}
    )
    with op.batch_alter_table('gacha_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gacha_template_name'), ['name'], unique=True)

    op.create_table('scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.String(length=100), nullable=False),
    sa.Column('default_template_name', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene')),
    info={'bind_key': 'model'}
    )
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_scene_id'), ['scene_id'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qq', sa.String(length=32), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    info={'bind_key': 'model'}
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_qq'), ['qq'], unique=True)

    op.create_table('checkin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_checkin_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkin')),
    info={'bind_key': 'model'}
    )
    with op.batch_alter_table('checkin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_checkin_date'), ['checkin_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_user_id'), ['user_id'], unique=False)

    op.create_table('gacha_banner_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['gacha_template.id'], name=op.f('fk_gacha_banner_pool_template_id_gacha_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gacha_banner_pool')),
    sa.UniqueConstraint('template_id', 'name', name=op.f('uq_gacha_banner_pool_template_id')),
    info={'bind_key': 'model'}
    )
    with op.batch_alter_table('gacha_banner_pool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gacha_banner_pool_template_id'), ['template_id'], unique=False)

    op.create_table('gacha_rarity',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False, comment='稀有度权重，同模板下合计须为 100'),
    sa.ForeignKeyConstraint(['template_id'], ['gacha_template.id'], name=op.f('fk_gacha_rarity_template_id_gacha_template')),
    sa.PrimaryKeyConstraint('template_id', 'name', name=op.f('pk_gacha_rarity')),
    info={'bind_key': 'model'}
    )
    op.create_table('user_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deposit', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('interest_last_claim_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_wallet_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_wallet')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_wallet_user_id')),
    info={'bind_key': 'model'}
    )
    with op.batch_alter_table('user_wallet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_wallet_user_id'), ['user_id'], unique=False)

    op.create_table('gacha_banner_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_pool_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='为空表示永久开放'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['banner_pool_id'], ['gacha_banner_pool.id'], name=op.f('fk_gacha_banner_run_banner_pool_id_gacha_banner_pool')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gacha_banner_run')),
    info={'bind_key': 'model'}
    )
    with op.batch_alter_table('gacha_banner_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gacha_banner_run_banner_pool_id'), ['banner_pool_id'], unique=False)

    op.create_table('gacha_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rarity_name', sa.Text(), nullable=False, comment='卡片稀有度，FK 至 gacha_rarity(template_id, name)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id', 'rarity_name'], ['gacha_rarity.template_id', 'gacha_rarity.name'], name=op.f('fk_gacha_item_template_id_gacha_rarity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gacha_item')),
    sa.UniqueConstraint('template_id', 'name', name=op.f('uq_gacha_item_template_id')),
    info={'bind_key': 'model'}
    )
    with op.batch_alter_table('gacha_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gacha_item_template_id'), ['template_id'], unique=False)

    op.create_table('gacha_banner_run_rate',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rarity_name', sa.Text(), nullable=False),
    sa.Column('up_share', sa.Integer(), nullable=False, comment='该稀有度中分配给 UP 卡的百分比（1-100）'),
    sa.ForeignKeyConstraint(['run_id'], ['gacha_banner_run.id'], name=op.f('fk_gacha_banner_run_rate_run_id_gacha_banner_run')),
    sa.PrimaryKeyConstraint('run_id', 'rarity_name', name=op.f('pk_gacha_banner_run_rate')),
    info={'bind_key': 'model'}
    )
    op.create_table('gacha_drop_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('banner_pool_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('scene_type', sa.Enum(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('draw_index', sa.Integer(), nullable=False, comment='同一批次抽卡内的顺序'),
    sa.Column('score_cost', sa.Integer(), nullable=False, comment='本条掉落对应消耗积分'),
    sa.ForeignKeyConstraint(['banner_pool_id'], ['gacha_banner_pool.id'], name=op.f('fk_gacha_drop_record_banner_pool_id_gacha_banner_pool')),
    sa.ForeignKeyConstraint(['item_id'], ['gacha_item.id'], name=op.f('fk_gacha_drop_record_item_id_gacha_item')),
    sa.ForeignKeyConstraint(['template_id'], ['gacha_template.id'], name=op.f('fk_gacha_drop_record_template_id_gacha_template')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_gacha_drop_record_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gacha_drop_record')),
    info={'bind_key': 'model'}
    )
    with op.batch_alter_table('gacha_drop_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gacha_drop_record_banner_pool_id'), ['banner_pool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gacha_drop_record_draw_date'), ['draw_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_gacha_drop_record_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gacha_drop_record_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gacha_drop_record_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gacha_drop_record_user_id'), ['user_id'], unique=False)

    op.create_table('gacha_banner_run_rate_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rarity_name', sa.Text(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['gacha_item.id'], name=op.f('fk_gacha_banner_run_rate_item_item_id_gacha_item')),
    sa.ForeignKeyConstraint(['run_id', 'rarity_name'], ['gacha_banner_run_rate.run_id', 'gacha_banner_run_rate.rarity_name'], name=op.f('fk_gacha_banner_run_rate_item_run_id_gacha_banner_run_rate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gacha_banner_run_rate_item')),
    sa.UniqueConstraint('run_id', 'item_id', name=op.f('uq_gacha_banner_run_rate_item_run_id')),
    info={'bind_key': 'model'}
    )
    with op.batch_alter_table('gacha_banner_run_rate_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gacha_banner_run_rate_item_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gacha_banner_run_rate_item_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gacha_banner_run_rate_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gacha_banner_run_rate_item_run_id'))
        batch_op.drop_index(batch_op.f('ix_gacha_banner_run_rate_item_item_id'))

    op.drop_table('gacha_banner_run_rate_item')
    with op.batch_alter_table('gacha_drop_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gacha_drop_record_user_id'))
        batch_op.drop_index(batch_op.f('ix_gacha_drop_record_template_id'))
        batch_op.drop_index(batch_op.f('ix_gacha_drop_record_scene_id'))
        batch_op.drop_index(batch_op.f('ix_gacha_drop_record_item_id'))
        batch_op.drop_index(batch_op.f('ix_gacha_drop_record_draw_date'))
        batch_op.drop_index(batch_op.f('ix_gacha_drop_record_banner_pool_id'))

    op.drop_table('gacha_drop_record')
    op.drop_table('gacha_banner_run_rate')
    with op.batch_alter_table('gacha_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gacha_item_template_id'))

    op.drop_table('gacha_item')
    with op.batch_alter_table('gacha_banner_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gacha_banner_run_banner_pool_id'))

    op.drop_table('gacha_banner_run')
    with op.batch_alter_table('user_wallet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_wallet_user_id'))

    op.drop_table('user_wallet')
    op.drop_table('gacha_rarity')
    with op.batch_alter_table('gacha_banner_pool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gacha_banner_pool_template_id'))

    op.drop_table('gacha_banner_pool')
    with op.batch_alter_table('checkin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_user_id'))
        batch_op.drop_index(batch_op.f('ix_checkin_checkin_date'))

    op.drop_table('checkin')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_qq'))
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))

    op.drop_table('user')
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_scene_id'))

    op.drop_table('scene')
    with op.batch_alter_table('gacha_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gacha_template_name'))

    op.drop_table('gacha_template')
    op.drop_table('config')
    # ### end Alembic commands ###
